# Project information
site_name: HELIX Documentation
site_description: API Documentation & Tutorials for the HELIX Platform.
site_author: Hypersonic Laboratories

# Site URL
site_url: https://development.helix-documentation.pages.dev #Can add ENV flag, e.g. !ENV [MKDOCS_SITE_URL, "https://development.helixdocs-1s1.pages.dev/"]

# Repository (for editing pages)
repo_url: https://github.com/hypersonic-laboratories/helix-documentation
edit_uri: edit/development/docs/

# Copyright
copyright: "&copy; 2024 HELIX&trade; is a trademark of Hypersonic Labs"

###------------------------------If you add or remove a page, you must update it here!!!-------------------------------------------------###
nav:
  - Getting Started:
    - getting_started/welcome.md
    - Start Here:
      - getting_started/install.md
      - getting_started/creatorTools.md
      - getting_started/help.md
      - getting_started/firstGame.md
    - Coming From Other Platforms:
      # - getting_started/comingGmod.md
      - getting_started/comingGTA.md
    - Discipline Hubs:
      - getting_started/scripters.md
      - getting_started/modelers.md
      # - getting_started/mappers.md
      # - getting_started/animators.md
      - getting_started/serverOwners.md
  - Tutorials:
    - tutorials/tutorialHome.md
    - General Tutorials:
      # - tutorials/serverClient.md
      - ... | flat | tutorials/tutorialImports/*.md
      - ... | flat | tutorials/tutorialImports/creating-assets/*.md
      - World Creation:
        - ... | flat | tutorials/tutorialImports/world-creation/*.md
      - Character:
        - ... | flat | tutorials/tutorialImports/creating-assets/characters/*.md
      - HSimpleVehicle:
        - ... | flat | tutorials/tutorialImports/creating-assets/HSimpleVehicle/*.md
    - Reference:
      # - tutorials/betterPractices.md
      - ... | flat | tutorials/referenceImports/*.md
      - Servers:
        - ... | flat | tutorials/referenceImports/server-manual/*.md
      - Default Assets:
        - ... | flat | tutorials/referenceImports/default-asset-pack/*.md
  - Scripting:
    - scripting/scriptingHome.md
    - scripting/introLua.md
    - scripting/luaStyleGuide.md
    - scripting/qbcore.md
    - Core Concepts:
      - ... | flat | scripting/coreConceptsImports/*.md
    - Code Examples:
      - tutorials/doors.md
      - ... | flat | tutorials/exampleImports/*.md
  - API:
    - api/apiHome.md
    - Glossary:
      - ... | flat | api/apiImport/glossary/*.md
    - Classes:
      - Base Classes:
        - ... | flat | api/apiImport/classes/base-classes/*.md
      - Static Classes:
        - ... | flat | api/apiImport/static-classes/*.md
      - Utility Classes:
        - ... | flat | api/apiImport/utility-classes/*.md
      - All Other Classes:
        - ... | flat | api/apiImport/classes/*.md
    - Structs:
      - ... | flat | api/apiImport/structs/*.md
    # - api/apiDetails.md


# Extra styling
# https://squidfunk.github.io/mkdocs-material/customization/?h=#additional-css
extra_css:
  - _extra/css/extra.css
  # Can add more here

# Extra functionality
# https://squidfunk.github.io/mkdocs-material/customization/?h=#additional-javascript
extra_javascript:
  - _extra/javascript/extra.js
  # Can add more here

# Validate links with logging tags
# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: ignore
  links:
    not_found: warn
    absolute_links: ignore
    unrecognized_links: info

# Add snippets #TODO: enable, but need to configure build to watch
# watch:
#   - _snippets

# MkDocs-Material Theme + customization
theme:
  name: material
  custom_dir: _overrides
  language: en
  font:
    text: Inter
    code: JetBrains Mono
  favicon: _images/favicon.ico
  logo: _images/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate-helix #toggle between 'slate' (default dark) and 'helix' (custom) and 'helix-slate' (custom, less dark)
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit #Also adds comment issue button, via _overrides/partials/actions.html
    
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks
    - content.code.annotate
    - content.code.copy

    # https://squidfunk.github.io/mkdocs-material/reference/tooltips/#improved-tooltips
    - content.tooltips

    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=footer#navigation
    - navigation.footer

    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow

  # static_templates: #disabled for now
  #   - 404.html #TODO

  #TODO: don't include MkDocs' JS?

extra:
  status:
    placeholder: Placeholder (Mostly Empty)
    wip: Work In Progress
    change: Subject To Change
    new: New Content!
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY #TODO
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by using our
            using our <a href="https://github.com/hypersonic-laboratories/helix-documentation/issues/new" target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie Consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  generator: false #No mention of MkDocs-Material in footer
  social: #TODO: ACTUAL LINKS, not just placeholders
    - icon: fontawesome/brands/discord
      link: https://discord.helixgame.com
      name: Discord
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/HELIXGames
      name: YouTube
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/HELIXGame
      name: Reddit
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/helixgame
      name: Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/helixgame
      name: Instagram
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/helixgame
      name: Twitter
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/helixgame
      name: Twitch
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@helixgame
      name: TikTok

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  # Note some are replaced by https://facelessuser.github.io/pymdown-extensions/extensions/blocks/
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify #if yaml syntax errors: safe to ignore
        kwds:
          case: lower
      anchorlink: false
      permalink: "#"
  - tables

  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  # https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.blocks.admonition: #ignore yml errors
      types:
        - note
        - info
        - tip
        - question
        - warning
        - danger
  - pymdownx.details
  # - pymdownx.blocks.details #not working
  - pymdownx.blocks.definition #ignore yml errors
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.caret:
      smart_insert: true
      insert: true
      superscript: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.escapeall #ignore yml errors
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys:
      separator: +
      strict: false
      camel_case: true
  - pymdownx.magiclink:
      user: maxswell-helix
      provider: github
      repo: HelixDocs
      repo_url_shorthand: true
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.pathconverter #ignore yml errors
  - pymdownx.progressbar #ignore yml errors
  - pymdownx.saneheaders #ignore yml errors
  - pymdownx.smartsymbols
  - pymdownx.snippets: #TODO: configure
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:
      smart_delete: true
      delete: true
      subscript: true

# https://squidfunk.github.io/mkdocs-material/plugins/
plugins:
  # Included
  - search
  # - tags:
  #     enabled: true #can enable later

  # Custom below here - NEED TO INSTALL

  # https://squidfunk.github.io/mkdocs-material/reference/images/#lightbox
  # https://github.com/blueswen/mkdocs-glightbox
  - glightbox:
      touchNavigation: false
      loop: false
      effect: zoom
      slide_effect: none
      width: auto
      height: auto
      zoomable: false
      draggable: false
      auto_caption: false
      caption_position: bottom

  # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
  - git-revision-date-localized

  # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
  - awesome-pages

  # https://github.com/mkdocs/mkdocs-redirects
  - redirects:
      redirect_maps:
        'index.md': 'getting_started/welcome.md'

  # https://github.com/orbikm/mkdocs-ezlinks-plugin
  # - ezlinks #disabled for now, was causing issues #ignore yml errors

  # TODO: setup minify, e.g.
  # - minify:
  #     minify_html: !ENV MKDOCS_MINIFY